version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: first_elt_db
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PWD
    volumes:
      - first_elt_db:/var/lib/postgresql/data
    ports:
      - $DB_HOST:$DB_PORT:5432

volumes:
  first_elt_db:
